<a href="https://www.tensorflow.org/?hl=pt-br"><img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/TensorFlowLogo.svg/1280px-TensorFlowLogo.svg.png" width = 250, align = "center"></a>

<h1 align=center><font size = 8><strong> Introdução ao TensorFlow</strong></font></h1>

<div class="alert alert-block alert-info" style="margin-top: 20px">
<font size = 5><strong>Nesse notebook iremos fazer uma revisão em conceitos básicos de TensorFlow, aprender suas estruturas e ver com elas a motivação para usa-las:</strong></font><br>
<br>
<p><a href="#ref1">Instalando TensorFlow</a></p>    
<p><a href="#ref2">Como funciona o TensorFlow?</a></p>
<p><a href="#ref3">Construindo um grafo</a></p>
<p><a href="#ref4"> Definindo vetores multidimensionais usando o TensorFlow</a></p>
<p><a href="#ref5">Por que Tensores?</a></p>
<p><a href="#ref6">Variaveis</a></p>
<p><a href="#ref7">Placeholders</a></p>
<p><a href="#ref8">Operações</a></p>
<p></p>
</div>
<br>






----------------

<a id="ref1"></a>
# Instalando TensorFlow

<h2> No Ubuntu</h2>
    <p>Com o pip já instalado basta usar esse comando no terminal: <strong>sudo pip/pip3 install tensorflow</strong></p>
<h2> No Windows</h2>
    <p>Recomendo baixar o Anaconda versão 5.20 para o python 3.6 nesse link: <a href="https://repo.anaconda.com/archive/"> https://repo.anaconda.com/archive/</a> </p> 
<h2> No Mac </h2>
    <p>Viste o seguinte endereço: <a href="https://www.tensorflow.org/install/source">https://www.tensorflow.org/install/source</a></p>

-----------------------------------

<a id="ref2"></a>
# Como funciona o TensorFlow?

<strong>TensorFlow tem a capacidade de executar seu código em diferentes componetes tanto em CPUs quanto em GPUs isso é uma consequência da sua estrutura específica:</strong>
     <p> -> TensorFlow define a computação como grafos, e esse são feito através de operações( também conhecidas como "ops"). Então, quando trabalhamos com TensorFlow, é a mesma coisa de termos a definição de uma série de operações em um grafo de execução.</p>
     <p>-> Para executar essas operações como computações, nos devemos lançar nosso grafo em uma sessão. A sessão traduz e passa as operações representando o grafo para o dispositivo que você deseja que execute, seja ele GPU ou CPU</p>
     <p>-> Por exemplo, a imagem abaixo representa um grafo em TensorFlow. _W_,_x_ e b são os tensores sobre as bordas do grafo. _MatMul_ é a operação a ser executada sobre os tensores _W_ e _x_, depois de _Add_ é chamada e adicionar o resultado do operador anterior com _b_. Os tensores resultantes de cada operação cruzam com o próximo até o final, onde  é possível obter o resultado desejado.</p> 


<img src='https://ibm.box.com/shared/static/a94cgezzwbkrq02jzfjjljrcaozu5s2q.png'>


------------------------------

# Importando TensorFlow

In [1]:
import tensorflow as tf

-----------------

<a id="ref3"></a>
# Construindo o Grafo

Como falamos anteriomente, TensorFlow funciona como modelo de grafo de execução. Vamos criar nosso primeiro grafo

Para criar nosso primeiro grafo nos iremos utilizar _source operations_, com a qual não precisamos qualquer informação de entrada. 

Essas operações bases or _source ops_ passarão essa informação para outros operadores com qual executarão os calculos.

Para criar essas duas operações bases que produzirão números, definiremos duas constantes::


In [2]:
a = tf.constant([2])
b = tf.constant([3])

Apos isso, vamos fazer a operação em cima das variaveis. A função _tf.add()_ adiciona dois elementos ( você também pode usar `c = a + b`). 

In [3]:
c = tf.add(a,b)
#c = a + b é também uma forma de definir a soma dos termos

Então o TensorFlow precisa que incializemos uma sessão para rodar nosso código. Sessões são, de certa forma, um contexto para criar um grafo de execução no TensorFlow. Vamos definir nossa sessão:

In [4]:
session = tf.Session()

Vamos rodar essa sessão para conseguir o resultado da operação realizada em "c":

In [5]:
result = session.run(c)
print(result)

[5]


Feche a sessão para liberar os recursos:

In [6]:
session.close()

Para evitar de fechar sessões toda vez, nos podemos definir então um bloco _with, que depois de rodar o bloco _with a sessão finalizará automaticamente:

In [7]:
with tf.Session() as session:
    result = session.run(c)
    print(result)

[5]


Mesmo esse exemplo tolo de adicionar 2 constantes para alcançar um resultado simples define a base do TensorFlow. Defina sua base (neste caso, nossas constantes), inclua nós (operações, como _tf.add_) e inicie uma sessão para construir um gráfico.

### Qual o significado de um Tensor?

<div class="alert alert-success alertsuccess" style="margin-top: 20px">
<font size = 3><strong>No TensorFlow todo o conjunto de dados é passado entre operações no grafo de execução, e esse são passados na forma de tensores, daí o nome TensorFlow </strong></font>
<br>
<br>
    
A palavra _tensor_ em latim significa " aquili que se estende". Isso é um objeto matemático chamado de _tensor" pois a aplicação inicial de tensores era o estudo de materiais que se estendiam sobre tensão. O significado contemporâneo dos tensores pode ser tomado como matrizes multidimensionais.     
<p></p>

</div>
Isso é ótimo, mas...o que são essas matrizes multidimensionais?

Voltando um pouco para física para entender o conceito de dimensão:<br>
<img src="https://ibm.box.com/shared/static/ymn0hl3hf8s3xb4k15v22y5vmuodnue1.svg"/>
<div style="text-align:center">[[Image Source]](https://en.wikipedia.org/wiki/Dimension) </div>

A dimensão zero pode ser vista como um ponto, um único objeto ou um elemento.
 
A primeira dimensão um pode ser uma linha, um vetor de uma dimensão pode ser visto como vários numeros sobre uma linha, ou como pontos sobre uma linha. Uma dimensão pode conter infinitos pontos de dimensão zero.

A segunda dimensão pode ser vista como uma superfície, uma matriz bidimensional pode ser vista como uma série infinita de linhas ao longo de uma linha infinita.

A terceira dimensão pode ser vista como volume, uma matriz tridimensional pode ser vista como uma série infinita de superfícies ao longo de uma linha infinita.

A quarta dimensão pode ser vista como o hiperespaço ou o espaço-tempo, um volume que varia ao longo do tempo ou uma série infinita de volumes ao longo de uma linha infinita. E assim por diante ...


Como objetos matemáticos: <br><br>
<img src="https://ibm.box.com/shared/static/kmxz570uai8eeg6i6ynqdz6kmlx1m422.png">
<div style="text-align:center">[[Image Source]](https://book.mql4.com/variables/arrays)</div>

Resumindo:<br><br>
<table style="width:100%">
  <tr>
    <td><b>Dimensão</b></td>
    <td><b>Representação Física</b></td> 
    <td><b>Objeto matemático</b></td>
    <td><b>No código</b></td>
  </tr>
  
  <tr>
    <td>Zero </td>
    <td>Ponto</td> 
    <td>Escalar (Um numero)</td>
    <td>[ 1 ]</td>
  </tr>

  <tr>
    <td>Um</td>
    <td>Linha</td> 
    <td>Vetor (Sequência de números) </td>
    <td>[ 1,2,3,4,... ]</td>
  </tr>
  
   <tr>
    <td>Dois</td>
    <td>Superfície</td> 
    <td>Matrix (Tabela de números)</td>
    <td>[ [1,2,3,4,...], [1,2,3,4,...], [1,2,3,4,...],... ]</td>
  </tr>
  
   <tr>
    <td>Três</td>
    <td>Volume</td> 
    <td>Tensor (Cubo de números)</td>
    <td>[ [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...] ,...]... ]</td>
  </tr>
  
</table>

-----------------

<a id="ref4"></a>
# Definindo vetores multidimensionais usando o TensorFlow
Agora vamos tentar definir essas matrizes usando o TensorFlow:

In [8]:
Scalar = tf.constant([2])
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session() as session:
    result = session.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = session.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = session.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = session.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 [2] 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



Agora que você entende essas estruturas de dados, convido-o a brincar com elas usando algumas funções anteriores para ver como elas se comportarão, de acordo com seus tipos de estrutura:

In [9]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

first_operation = tf.add(Matrix_one, Matrix_two)
second_operation = Matrix_one + Matrix_two

with tf.Session() as session:
    result = session.run(first_operation)
    print ("Definido usando a função do tensorflow:")
    print(result)
    result = session.run(second_operation)
    print ("Definido usando expressões normais:")
    print(result)

Definido usando a função do tensorflow:
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Definido usando expressões normais:
[[3 4 5]
 [4 5 6]
 [5 6 7]]


Com a definição de símbolo regular e também a função TensorFlow, conseguimos obter uma multiplicação baseada em elementos, também conhecida como produto Hadamard.

Mas e se quisermos o produto de matriz regular?

Então, precisamos usar outra função do TensorFlow chamada __tf.matmul()__:

In [10]:
Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_two = tf.constant([[2,3],[3,4]])

first_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session() as session:
    result = session.run(first_operation)
    print ("Definido usando a função do tensorflow:")
    print(result)

Definido usando a função do tensorflow:
[[13 18]
 [18 25]]


Nós também podemos definir essa multiplicação, mas existe uma função que já faz isso, então não há necessidade de reinventar a roda!

---------------

<a id="ref5"></a>
# Por que Tensores?

A estrutura Tensor nos ajuda, dando a liberdade de moldar o conjunto de dados da maneira que queremos.

E é particularmente útil ao lidar com imagens, devido à natureza de como as informações nas imagens são codificadas,

Pensando em imagens, é fácil entender que ela tem altura e largura, por isso faria sentido representar as informações contidas nela com uma estrutura bidimensional (uma matriz) ... até que você se lembre de que as imagens têm cores e Para adicionar informações sobre as cores, precisamos de outra dimensão, e isso acontece quando os Tensores se tornam particularmente úteis.

As imagens são codificadas em canais de cores, os dados da imagem são representados em cada intensidade de cor em um canal de cor em um determinado ponto, sendo o mais comum o RGB, que significa Vermelho, Azul e Verde. A informação contida em uma imagem é a intensidade de cada cor de canal na largura e altura da imagem, assim:

<img src='https://ibm.box.com/shared/static/xlpv9h5xws248c09k1rlx7cer69y4grh.png'>
<div style="text-align:center">[[Image Source]](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424131.aspx)</div>

Então a intensidade do canal vermelho em cada ponto com largura e altura pode ser representada em uma matriz, o mesmo vale para os canais azul e verde, então acabamos tendo três matrizes, e quando estas são combinadas elas formam um tensor.


-----------------------

<a id="ref6"></a>
# Variáveis

Agora que estamos mais familiarizados com a estrutura de dados, vamos dar uma olhada em como o TensorFlow lida com as variáveis.

Para definir variáveis, usamos o comando __tf.variable () __.
Para poder usar variáveis em um gráfico de computação, é necessário inicializá-las antes de executar o gráfico em uma sessão. Isso é feito executando __tf.global_variables_initializer () __.

Para atualizar o valor de uma variável, simplesmente executamos uma operação de atribuição que atribui um valor à variável:

In [11]:
state = tf.Variable(0)

Vamos primeiro criar um contador simples, uma variável que aumenta uma unidade de cada vez:

In [12]:
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

As variáveis devem ser inicializadas executando uma operação de inicialização após o lançamento do gráfico. Primeiro, precisamos adicionar a operação de inicialização ao gráfico:

In [13]:
init_op = tf.global_variables_initializer()

Em seguida, iniciamos uma sessão para executar o gráfico, primeiro inicializamos as variáveis, depois imprimimos o valor inicial da variável __state__ e, em seguida, executamos a operação de atualização da variável __state__ e imprimimos o resultado após cada atualização:

In [14]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(state))
    for _ in range(3):
        session.run(update)
        print(session.run(state))

0
1
2
3


-----------------

<a id="ref7"></a>
# Placeholders

Agora sabemos como manipular variáveis dentro do TensorFlow, mas e quanto a alimentar dados fora de um modelo do TensorFlow?

Se você quiser alimentar dados para um modelo TensorFlow de fora de um modelo, precisará usar marcadores de posição.

Então, quais são esses espaços reservados e o que eles fazem?

Os espaços reservados podem ser vistos como "buracos" em seu modelo, "buracos" aos quais você passará os dados, você pode criá-los usando <br/> <b> tf.placeholder (_datatype _) </ b>, onde <b> _datatype _ </ b> especifica o tipo de dados (inteiros, pontos flutuantes, cadeias de caracteres, booleanos) junto com seus bits de precisão (8, 16, 32, 64).

A definição de cada tipo de dados com a respectiva sintaxe de python é definida como:

|Data type	|Python type|Description|
| --------- | --------- | --------- |
|DT_FLOAT	|tf.float32	|32 bits floating point.|
|DT_DOUBLE	|tf.float64	|64 bits floating point.|
|DT_INT8	|tf.int8	|8 bits signed integer.|
|DT_INT16	|tf.int16	|16 bits signed integer.|
|DT_INT32	|tf.int32	|32 bits signed integer.|
|DT_INT64	|tf.int64	|64 bits signed integer.|
|DT_UINT8	|tf.uint8	|8 bits unsigned integer.|
|DT_STRING	|tf.string	|Variable length byte arrays. Each element of a Tensor is a byte array.|
|DT_BOOL	|tf.bool	|Boolean.|
|DT_COMPLEX64	|tf.complex64	|Complex number made of two 32 bits floating points: real and imaginary parts.|
|DT_COMPLEX128	|tf.complex128	|Complex number made of two 64 bits floating points: real and imaginary parts.|
|DT_QINT8	|tf.qint8	|8 bits signed integer used in quantized Ops.|
|DT_QINT32	|tf.qint32	|32 bits signed integer used in quantized Ops.|
|DT_QUINT8	|tf.quint8	|8 bits unsigned integer used in quantized Ops.|

<div style="text-align:center">[[Table Source]](https://www.tensorflow.org/versions/r0.9/resources/dims_types.html)</div>


Então, criamos um marcador:

In [15]:
a = tf.placeholder(tf.float32)

And define a simple multiplication operation:

In [16]:
b = a*2

Now we need to define and run the session, but since we created a "hole" in the model to pass the data, when we initialize the session we are obligated to pass an argument with the data, otherwise we would get an error.

To pass the data to the model we call the session with an extra argument <b> feed_dict</b> in which we should pass a dictionary with each placeholder name folowed by its respective data, just like this:

In [17]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:3.5})
    print (result)

7.0


Como os dados em TensorFlow são passados na forma de matrizes multidimensionais, podemos passar qualquer tipo de tensor através dos espaços reservados para obter a resposta para a simples operação de multiplicação:

In [18]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


------------------------

<a id="ref8"></a>
# Operações

Operações nos nós que representam as operações matemáticas sobre os tensores em um gráfico. Essas operações podem ser qualquer tipo de função, como somar e subtrair o tensor ou talvez uma função de ativação.

_tf.matmul_, _tf.add_, _tf.nn.sigmoid_ são algumas das operações no TensorFlow. Estes são como funções em python, mas operam diretamente sobre tensores e cada um faz uma coisa específica.
<div class="alert alert-success alertsuccess" style="margin-top: 20px">Other operations can be easily found in: https://www.tensorflow.org/versions/r0.9/api_docs/python/index.html</div>

In [19]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)

with tf.Session() as session:
    result = session.run(c)
    print ('c =: %s' % result)
    result = session.run(d)
    print ('d =: %s' % result)

c =: [7]
d =: [3]


-------------------------

# Agradecimentos e Indicações

<a href="https://www.bigdatauniversity.com"><img src = "https://ibm.box.com/shared/static/jvcqp2iy2jlx2b32rmzdt0tx8lvxgzkp.png" width = 300, align = "center"></a><br>
<p>Este notebook foi desenvolvido graças ao curso de "Deep Learning with TensorFlow" da Cognitive Class.</p>
<p>Segue o link do curso original:<br><a href="https://cognitiveclass.ai/courses/deep-learning-tensorflo"> https://cognitiveclass.ai/courses/deep-learning-tensorfl </a> </p>

<a href="https://www.udemy.com/"><img src = "https://www.udemy.com/staticx/udemy/images/v6/default-meta-image.png" width = 300, align = "center"></a><br>
<p>Segue aqui indicações de bons cursos sobre TensorFlow na plataforma paga Udemy</p>
<p>TensorFlow: Machine Learning e Deep Learning com Python:<br><a href="https://www.udemy.com/tensorflow-machine-learning-deep-learning-python/">https://www.udemy.com/tensorflow-machine-learning-deep-learning-python/</a></p>
<p>Complete Guide to TensorFlow for Deep Learning with Python:<br><a href="https://www.udemy.com/complete-guide-to-tensorflow-for-deep-learning-with-python/">https://www.udemy.com/complete-guide-to-tensorflow-for-deep-learning-with-python/</a></p>

-----------------------------