<h1 align=center><font size = 8><strong>Exemplo regressão logística</strong></font></h1>

# Imports

In [1]:
from __future__ import division, print_function, unicode_literals
import math
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
%matplotlib inline

# Pré-processamento

In [2]:
iris = load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
non_versicolor_labels = [0 for i in range(100)]
versicolor_labels = [1 for i in range(50)]

In [6]:
y = np.concatenate([non_versicolor_labels, versicolor_labels])

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Divisão de conjuntos de treino e teste

In [8]:
perm = np.random.permutation(150)

In [9]:
x_train, x_test = X[perm][20:], X[perm][:20]
y_train, y_test = y[perm][20:], y[perm][:20]

In [10]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 4), (130,), (20, 4), (20,))

In [11]:
y_train = y_train.reshape(-1,1)
y_test = y_test.reshape(-1,1)

In [12]:
x_train = x_train[:, 2:]
x_test = x_test[:, 2:]

In [13]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 2), (130, 1), (20, 2), (20, 1))

In [14]:
# plt.plot(x_train[:,0], x_train[:,1], 'b.')
# plt.plot(x_train[:,0], x_train[:,1], 'r.')
# plt.xlabel('Petal Legth (cm)')
# plt.ylabel('Petal Width (cm)')
# plt.legend(['Versicolor','Not Versicolor'])
# plt.show()

# Definindo funções logística e a função de custo

In [15]:
def logits(x):
    return 1 / (1 + np.e**(-x))

In [16]:
def logistic_loss(y, y_hat):
    return -np.mean(y*np.log(y_hat)+(1-y) * np.log(1 - y_hat))

# Definindo pesos e bias

In [17]:
W = np.zeros((2,1))
b = np.zeros((1,1))
learning_rate = 0.1

# Rodando modelo Iterativo

In [18]:
m = len(y_train)

for epoch in range(100):
    Z = np.matmul(x_train, W) + b
    A = logits(Z)
    loss = logistic_loss(y_train, A)
    dz = A - y_train
    dw = 1/m * np.matmul(x_train.T, dz)
    db = np.sum(dz)
    
    W = W - learning_rate * dw
    b = b - learning_rate * db
    
    if epoch % 1000 == 0:
        print(loss)

0.6931471805599453


# Peso e bias finais

In [19]:
W, b

(array([[1.46703259],
        [0.85707639]]), array([[-8.60385796]]))

# Calculando y_predito

In [20]:
y_preds = []
for i in logits(Z):
    if i > 0.5:
        y_preds.append(1)
    else:
        y_preds.append(0)

# Obtendo acurárica

In [21]:
correct = 0 
for i in range(len(y_train)):
    if y_train[i] == y_preds[i]:
        correct +=1
acc = (correct/float(len(y_train)))*100        
        
print(acc)

96.15384615384616


-----------------------------------

<h1 align=center><font size = 8><strong>Exemplo regressão logística com scikit learn</strong></font></h1>

<a href="https://scikit-learn.org/stable/"><img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Scikit_learn_logo_small.svg/260px-Scikit_learn_logo_small.svg.png" width = 250, align = "center"></a>

- Métricas:

   Acurácia:<br>https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score

# Imports

In [24]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.metrics import accuracy_score
%matplotlib inline

# Pré-processamento

In [25]:
iris = load_iris()

In [26]:
X = iris.data
y = iris.target

In [27]:
non_versicolor_labels = [0 for i in range(100)]
versicolor_labels = [1 for i in range(50)]

In [28]:
y = np.concatenate([non_versicolor_labels, versicolor_labels])

# Divisão de conjunto de treino e teste

In [29]:
perm = np.random.permutation(150)

In [30]:
x_train, x_test = X[perm][20:], X[perm][:20]
y_train, y_test = y[perm][20:], y[perm][:20]

In [31]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 4), (130,), (20, 4), (20,))

In [32]:
y_train = y_train.reshape(-1,1)
y_test = y_test.reshape(-1,1)

In [33]:
x_train = x_train[:, 2:]
x_test = x_test[:, 2:]

In [34]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 2), (130, 1), (20, 2), (20, 1))

# Usando módulo LogisticRegression

In [35]:
logreg = LogisticRegression(C=1e5, solver='lbfgs',max_iter = 5000, tol = 0.0000001,multi_class='multinomial',verbose = 1)

In [36]:
# Create an instance of Logistic Regression Classifier and fit the data.
logreg.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=5000,
          multi_class='multinomial', n_jobs=None, penalty='l2',
          random_state=None, solver='lbfgs', tol=1e-07, verbose=1,
          warm_start=False)

# Calculando y_predito

In [37]:
y_preds = logreg.predict(x_train)

# Calculando Acurácia

In [38]:
accuracy_score(y_train, y_preds)

0.9692307692307692

-----------------------------

<h1 align=center><font size = 8><strong>Exemplo regressão logística com TensorFlow</strong></font></h1>

<a href="https://www.tensorflow.org/?hl=pt-br"><img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/TensorFlowLogo.svg/1280px-TensorFlowLogo.svg.png" width = 200, align = "center"></a>

# Imports

In [46]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.metrics import accuracy_score

# Pré-processamento

In [47]:
iris = load_iris()

In [48]:
X = iris.data
y = iris.target

In [49]:
non_versicolor_labels = [0 for i in range(100)]
versicolor_labels = [1 for i in range(50)]

In [50]:
y = np.concatenate([non_versicolor_labels, versicolor_labels])

# Divisão de conjunto de treino e teste

In [51]:
perm = np.random.permutation(150)

In [52]:
x_train, x_test = X[perm][20:], X[perm][:20]
y_train, y_test = y[perm][20:], y[perm][:20]

In [53]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 4), (130,), (20, 4), (20,))

In [54]:
y_train = y_train.reshape(-1,1)
y_test = y_test.reshape(-1,1)

In [55]:
x_train = x_train[:, 2:]
x_test = x_test[:, 2:]

In [56]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 2), (130, 1), (20, 2), (20, 1))

# Definindo Grafo