<h1 align=center><font size = 8><strong>Exemplo regressão logística</strong></font></h1>

# Imports

In [151]:
from __future__ import division, print_function, unicode_literals
import math
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
%matplotlib inline

# Pré-processamento

In [152]:
iris = load_iris()

In [153]:
X = iris.data
y = iris.target

In [154]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [155]:
non_versicolor_labels = [0 for i in range(100)]
versicolor_labels = [1 for i in range(50)]

In [156]:
y = np.concatenate([non_versicolor_labels, versicolor_labels])

In [157]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Divisão de conjuntos de treino e teste

In [158]:
perm = np.random.permutation(150)

In [159]:
x_train, x_test = X[perm][20:], X[perm][:20]
y_train, y_test = y[perm][20:], y[perm][:20]

In [160]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 4), (130,), (20, 4), (20,))

In [161]:
y_train = y_train.reshape(-1,1)
y_test = y_test.reshape(-1,1)

In [162]:
x_train = x_train[:, 2:]
x_test = x_test[:, 2:]

In [163]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 2), (130, 1), (20, 2), (20, 1))

# Definindo funções logística e a função de custo

In [164]:
def logits(x):
    return 1 / (1 + np.e**(-x))

In [165]:
def logistic_loss(y, y_hat):
    return -np.mean(y*np.log(y_hat)+(1-y) * np.log(1 - y_hat))

# Definindo pesos e bias

In [166]:
W = np.zeros((2,1))
b = np.zeros((1,1))
learning_rate = 0.1

# Rodando modelo Iterativo

In [167]:
m = len(y_train)

for epoch in range(100):
    Z = np.matmul(x_train, W) + b
    A = logits(Z)
    loss = logistic_loss(y_train, A)
    dz = A - y_train
    dw = 1/m * np.matmul(x_train.T, dz)
    db = np.sum(dz)
    
    W = W - learning_rate * dw
    b = b - learning_rate * db
    
    if epoch % 1000 == 0:
        print(loss)

0.6931471805599453


# Peso e bias finais

In [168]:
W, b

(array([[1.5322702 ],
        [0.87011919]]), array([[-8.93272667]]))

In [169]:
y_pred = np.matmul(x_test,W)+b

# Calculando y_predito

In [170]:
y_preds_adjust = []
for i in range(len(y_pred)):
    if y_pred[i] > 0.5:
        y_preds_adjust.append(1)
    else:
        y_preds_adjust.append(0)

# Obtendo acurárica

In [171]:
correct = 0 
for i in range(len(y_test)):
    if y_test[i] == y_preds_adjust[i]:
        correct +=1
acc = (correct/float(len(y_test)))*100        
        
print(acc)

95.0


-----------------------------------

<h1 align=center><font size = 8><strong>Exemplo regressão logística com scikit learn</strong></font></h1>

<a href="https://scikit-learn.org/stable/"><img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Scikit_learn_logo_small.svg/260px-Scikit_learn_logo_small.svg.png" width = 250, align = "center"></a>

- Métricas:

   Acurácia:<br>https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score

# Imports

In [24]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.metrics import accuracy_score
%matplotlib inline

# Pré-processamento

In [25]:
iris = load_iris()

In [26]:
X = iris.data
y = iris.target

In [27]:
non_versicolor_labels = [0 for i in range(100)]
versicolor_labels = [1 for i in range(50)]

In [28]:
y = np.concatenate([non_versicolor_labels, versicolor_labels])

# Divisão de conjunto de treino e teste

In [29]:
perm = np.random.permutation(150)

In [30]:
x_train, x_test = X[perm][20:], X[perm][:20]
y_train, y_test = y[perm][20:], y[perm][:20]

In [31]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 4), (130,), (20, 4), (20,))

In [32]:
y_train = y_train.reshape(-1,1)
y_test = y_test.reshape(-1,1)

In [33]:
x_train = x_train[:, 2:]
x_test = x_test[:, 2:]

In [34]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 2), (130, 1), (20, 2), (20, 1))

# Usando módulo LogisticRegression

In [35]:
logreg = LogisticRegression(C=1e5, solver='lbfgs',max_iter = 5000, tol = 0.0000001,multi_class='multinomial',verbose = 1)

In [36]:
# Create an instance of Logistic Regression Classifier and fit the data.
logreg.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=5000,
          multi_class='multinomial', n_jobs=None, penalty='l2',
          random_state=None, solver='lbfgs', tol=1e-07, verbose=1,
          warm_start=False)

# Calculando y_predito

In [37]:
y_preds = logreg.predict(x_train)

# Calculando Acurácia

In [38]:
accuracy_score(y_train, y_preds)

0.9692307692307692

-----------------------------

<h1 align=center><font size = 8><strong>Exemplo regressão logística com TensorFlow</strong></font></h1>

<a href="https://www.tensorflow.org/?hl=pt-br"><img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/TensorFlowLogo.svg/1280px-TensorFlowLogo.svg.png" width = 200, align = "center"></a>

# Imports

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

# Pré-processamento

In [7]:
iris = load_iris()

In [8]:
X = iris.data
y = iris.target

In [9]:
non_versicolor_labels = [0 for i in range(100)]
versicolor_labels = [1 for i in range(50)]

In [10]:
y = np.concatenate([non_versicolor_labels, versicolor_labels])

# Divisão de conjunto de treino e teste

In [11]:
perm = np.random.permutation(150)

In [12]:
x_train, x_test = X[perm][20:], X[perm][:20]
y_train, y_test = y[perm][20:], y[perm][:20]

In [13]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 4), (130,), (20, 4), (20,))

In [14]:
y_train = y_train.reshape(-1,1)
y_test = y_test.reshape(-1,1)

In [15]:
x_train = x_train[:, 2:]
x_test = x_test[:, 2:]

In [16]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((130, 2), (130, 1), (20, 2), (20, 1))

# Definindo hiper-parametros

In [17]:
learning_rate = 0.0005
n_epochs = 3000

# Resetando grafo

In [18]:
tf.reset_default_graph()

# Definindo Grafo

In [55]:
# place_X = tf.constant( X_train, dtype = tf.float32 ,name = "X")
# place_y = tf.constant(y_train, dtype = tf.float32,name = "y")
# place_X = tf.Variable( X_train, dtype = tf.float32 ,name = "X")
# place_y = tf.Variable( y_train, dtype = tf.float32 ,name = "y")
place_X = tf.placeholder(tf.float32,[None,2])
place_y = tf.placeholder(tf.float32,[None,1])

# Setando Variáveis

In [56]:
W = tf.Variable(tf.random_normal(shape=[2, 1])) 
b = tf.Variable(tf.random_normal(shape=[1,1])) 

# Definindo nossa predição

In [57]:
y_pred = tf.add(tf.matmul(place_X,W), b)

In [58]:
print(y_pred.shape)
print(place_y.shape)

(?, 1)
(?, 1)


# Definindo função de custo

In [59]:
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels = place_y , logits = y_pred))

# Definindo otimizador

In [60]:
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(loss)

# Inicializando as variáveis

In [61]:
init = tf.global_variables_initializer()

# Rodando nosso modelo na sessão

In [68]:
# # Rodando com tf.placeholder
# with tf.Session() as sess:
#     sess.run(init)
#     for epoch in range(n_epochs):
#         for (x,y) in zip(x_train, y_train):
#             sess.run(optimizer, feed_dict={place_X: x, place_y: y})
#         if (epoch+1) % 100 == 0:
#             c = sess.run(loss, feed_dict={place_X: x_train, place_y: y_train})
#             print("Epoch:", (epoch+1), "cost =", c)
            
#     w_final, b_final = sess.run([W,b])

In [67]:
# Rodando com tf.placeholder
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        sess.run(optimizer, feed_dict={place_X: x_train, place_y: y_train})
        if (epoch+1) % 100 == 0:
            c = sess.run(loss, feed_dict={place_X: x_train, place_y: y_train})
            print("Epoch:", (epoch+1), "cost =", c)
            
    w_final, b_final = sess.run([W,b])

Epoch: 100 cost = 1.5277779
Epoch: 200 cost = 1.3918111
Epoch: 300 cost = 1.2596717
Epoch: 400 cost = 1.1327534
Epoch: 500 cost = 1.0128365
Epoch: 600 cost = 0.90203816
Epoch: 700 cost = 0.80261457
Epoch: 800 cost = 0.7165832
Epoch: 900 cost = 0.6452295
Epoch: 1000 cost = 0.5887064
Epoch: 1100 cost = 0.5459372
Epoch: 1200 cost = 0.51489073
Epoch: 1300 cost = 0.4930811
Epoch: 1400 cost = 0.47804984
Epoch: 1500 cost = 0.46768486
Epoch: 1600 cost = 0.46034956
Epoch: 1700 cost = 0.4548738
Epoch: 1800 cost = 0.45047605
Epoch: 1900 cost = 0.44666475
Epoch: 2000 cost = 0.44314834
Epoch: 2100 cost = 0.4397635
Epoch: 2200 cost = 0.4364245
Epoch: 2300 cost = 0.43309024
Epoch: 2400 cost = 0.42974362
Epoch: 2500 cost = 0.4263796
Epoch: 2600 cost = 0.42299935
Epoch: 2700 cost = 0.4196063
Epoch: 2800 cost = 0.41620514
Epoch: 2900 cost = 0.41280067
Epoch: 3000 cost = 0.4093976


In [69]:
print(w_final)
print(b_final)

[[-0.28870517]
 [ 1.8139768 ]]
[[-1.5162541]]


In [72]:
y_pred = np.matmul(x_test,w_final)+b_final

In [78]:
y_preds_adjust = []

In [80]:
for i in range(len(y_pred)):
    if y_pred[i] > 0.5:
        y_preds_adjust.append(1)
    else:
        y_preds_adjust.append(0)

In [83]:
correct = 0 
for i in range(len(y_test)):
    if y_test[i] == y_preds_adjust[i]:
        correct +=1
acc = (correct/float(len(y_test)))*100        
        
print(acc)

85.0
