In [1]:
from __future__ import division

import numpy as np
import tensorflow as tf
from sklearn import preprocessing
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score


/home/lsbd/.local/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
dataAbalone = np.loadtxt("abalone.data", dtype = str, delimiter = ',')
linha = dataAbalone.shape[0]
coluna = dataAbalone.shape[1]

In [3]:
print("Shape: {},{}".format(linha,coluna))
dataAbalone

Shape: 4177,9


array([['M', '0.455', '0.365', ..., '0.101', '0.15', '15'],
       ['M', '0.35', '0.265', ..., '0.0485', '0.07', '7'],
       ['F', '0.53', '0.42', ..., '0.1415', '0.21', '9'],
       ...,
       ['M', '0.6', '0.475', ..., '0.2875', '0.308', '9'],
       ['F', '0.625', '0.485', ..., '0.261', '0.296', '10'],
       ['M', '0.71', '0.555', ..., '0.3765', '0.495', '12']], dtype='<U6')

In [4]:
np.random.shuffle(dataAbalone)

In [5]:
for i in range(linha):
    for j in range(coluna):
        if(dataAbalone[i,j] == "M"):
            dataAbalone[i,j] = 0
        if(dataAbalone[i,j] == "F"):
            dataAbalone[i,j] = 1
        if(dataAbalone[i,j] == "I"):
            dataAbalone[i,j] = 2

In [6]:
dataAbalone

array([['0', '0.445', '0.35', ..., '0.0695', '0.117', '8'],
       ['2', '0.235', '0.175', ..., '0.015', '0.02', '5'],
       ['0', '0.58', '0.465', ..., '0.1865', '0.385', '17'],
       ...,
       ['1', '0.6', '0.475', ..., '0.1695', '0.3205', '10'],
       ['0', '0.575', '0.445', ..., '0.1405', '0.237', '10'],
       ['0', '0.355', '0.26', ..., '0.0485', '0.055', '6']], dtype='<U6')

In [100]:
x = np.float32(dataAbalone[:,0:7])
#x = preprocessing.normalize(x, axis = 0, norm='max')
y = dataAbalone[:,8]

In [101]:
classes =  list(set(y))
print(classes)
print(len(classes))

['5', '1', '18', '4', '26', '10', '14', '20', '22', '9', '23', '2', '0', '15', '25', '13', '16', '11', '27', '12', '8', '19', '17', '21', '24', '6', '7', '3']
28


In [102]:
for y_index in range(len(y)):
    y[y_index] = classes.index(y[y_index])

In [103]:
print(y.shape)
print(y)

(4177,)
['7' '1' '8' ... '25' '25' '14']


In [104]:
Y_onehot = np.zeros(shape = [len(y), len(classes)])
print(np.shape(Y_onehot))

for y_index in range(len(y)):
    Y_onehot[y_index, int(y[y_index])] = 1

(4177, 28)


In [105]:
print(Y_onehot)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [106]:
#train
x_train = np.float32(x[0:3500, :])

#y_train = Y_onehot[0:3500, :]
y_train = Y_onehot[0:3500]

#test
x_test = np.float32(x[3500:4177, :])
#y_test = Y_onehot[3500:4177, :]
y_test = Y_onehot[3500:4177]


In [107]:
print((x_train))
print((y_train))
print((x_test))
print((y_test))

[[0.     0.445  0.35   ... 0.3615 0.1565 0.0695]
 [2.     0.235  0.175  ... 0.0705 0.0335 0.015 ]
 [0.     0.58   0.465  ... 1.035  0.401  0.1865]
 ...
 [0.     0.62   0.5    ... 1.3915 0.726  0.2795]
 [2.     0.45   0.35   ... 0.514  0.253  0.1045]
 [2.     0.46   0.335  ... 0.444  0.225  0.0745]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[2.     0.585  0.46   ... 0.7635 0.326  0.153 ]
 [0.     0.64   0.5    ... 1.273  0.5065 0.2925]
 [2.     0.605  0.49   ... 1.071  0.482  0.1935]
 ...
 [1.     0.6    0.475  ... 1.21   0.653  0.1695]
 [0.     0.575  0.445  ... 0.737  0.325  0.1405]
 [0.     0.355  0.26   ... 0.1905 0.081  0.0485]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [108]:
print(np.shape(x_train))
print(np.shape(y_train))
print(np.shape(x_test))
print(np.shape(y_test))

(3500, 7)
(3500, 28)
(677, 7)
(677, 28)


Network


In [158]:
tf.reset_default_graph()

In [159]:
X = tf.placeholder(dtype = tf.float32, shape = [None,7])
Y = tf.placeholder(dtype = tf.float32, shape = [None,len(classes)])

alpha = tf.placeholder(dtype = tf.float32, shape = None)

In [160]:
dense1 = tf.layers.dense(inputs = X, units = 10 ,activation =tf.nn.tanh)
dense2 = tf.layers.dense(inputs = dense1, units = 10, activation = tf.nn.tanh)
output_softmax = tf.layers.dense(inputs = dense2, units = len(classes), activation = tf.nn.softmax)

In [161]:
Y_original = tf.argmax(input=Y, axis=1)

In [162]:
a = np.array(list(range(len(classes))),dtype = np.float32)
a = np.reshape(a, [1,len(classes)])
print(a.shape)

(1, 28)


In [163]:
output_softmax

<tf.Tensor 'dense_2/Softmax:0' shape=(?, 28) dtype=float32>

In [164]:
loss1 = tf.matmul(a, tf.transpose(output_softmax))
print(loss1)
loss2 = tf.subtract(tf.cast(Y_original, dtype=tf.float32), loss1)
print(loss2)
loss3 = tf.multiply(loss2, loss2) # element-wise pow
print(loss3)
loss = tf.reduce_mean(loss3)
print(loss)

#loss = tf.subtract(tf.cast(Y,dtype=tf.float32),tf.pow( tf.matmul(a,tf.transpose(output)) ,2) ) 

Tensor("MatMul:0", shape=(1, ?), dtype=float32)
Tensor("Sub:0", shape=(1, ?), dtype=float32)
Tensor("Mul:0", shape=(1, ?), dtype=float32)
Tensor("Mean:0", shape=(), dtype=float32)


In [165]:
#loss = tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=output)

In [166]:
output = tf.argmax(input=output_softmax, axis=1)

In [167]:
trainer = tf.train.GradientDescentOptimizer(learning_rate= alpha)
#trainer = tf.train.AdamOptimizer(learning_rate= alpha)

train_operation = trainer.minimize(loss)

Create Session and execute the graph

In [168]:
train_epochs = 100000

sess = tf.Session()

In [169]:
sess.run(tf.global_variables_initializer())

for epoch in range(train_epochs):
    output_, loss_, Y_original_, train_operation_ = sess.run([output, loss, Y_original, train_operation],
                                               feed_dict={X: x_train, Y: y_train,
                                                         alpha: 0.015})
    
    if not (epoch % 100):
        print("epoch {}: {} - Accuracy: {}".format(epoch, loss_, accuracy_score(y_true=Y_original_, y_pred=np.round(output_))))

output_, Y_original_, loss_ = sess.run([output, Y_original, loss], feed_dict={X: x_test, Y: y_test})
print("TEST: {} - Accuracy: {}".format(loss_, accuracy_score(Y_original_, np.round(output_))))

epoch 0: 76.00350189208984 - Accuracy: 0.048857142857142856
epoch 100: 66.89299011230469 - Accuracy: 0.040285714285714286
epoch 200: 66.64472961425781 - Accuracy: 0.036571428571428574
epoch 300: 66.48311614990234 - Accuracy: 0.031714285714285716
epoch 400: 66.28671264648438 - Accuracy: 0.029714285714285714
epoch 500: 66.07418060302734 - Accuracy: 0.030857142857142857
epoch 600: 65.89464569091797 - Accuracy: 0.030285714285714287
epoch 700: 65.74847412109375 - Accuracy: 0.03
epoch 800: 65.60372924804688 - Accuracy: 0.021714285714285714
epoch 900: 65.44972229003906 - Accuracy: 0.017142857142857144
epoch 1000: 65.28787231445312 - Accuracy: 0.019428571428571427
epoch 1100: 65.12480163574219 - Accuracy: 0.022
epoch 1200: 64.9684066772461 - Accuracy: 0.026857142857142857
epoch 1300: 64.82247924804688 - Accuracy: 0.036571428571428574
epoch 1400: 64.68788146972656 - Accuracy: 0.04371428571428571
epoch 1500: 64.56522369384766 - Accuracy: 0.05342857142857143
epoch 1600: 64.45494842529297 - Accura

KeyboardInterrupt: 