<a href="https://www.tensorflow.org/?hl=pt-br"><img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/TensorFlowLogo.svg/1280px-TensorFlowLogo.svg.png" width = 250, align = "center"></a>

<h1 align=center><font size = 8><strong> Classificação com MLP</strong></font></h1>

# Import modules

In [3]:
import tensorflow as tf
import numpy as np
from sklearn.metrics import accuracy_score

### Load Dataset:

In [4]:
iris = np.loadtxt("iris.data.txt", dtype=str, delimiter=",")

In [5]:
print("Shape:", np.shape(iris))
print(iris)

Shape: (150, 5)
[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7' '0.5' 'Iris-setosa']


In [6]:
# shuffle data
np.random.shuffle(iris)

In [7]:
x = np.float32(iris[:, 0:4])
y = iris[:, 4]

### Dataset Pre-processing

In [8]:
classes = list(set(y))
print(classes)

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']


In [9]:
len(classes)

3

In [10]:
for y_index in range(len(y)):
    y[y_index] = classes.index(y[y_index])

In [11]:
print(y)

['1' '2' '1' '1' '0' '2' '0' '1' '1' '0' '0' '2' '1' '0' '0' '2' '1' '2'
 '0' '0' '0' '1' '2' '0' '1' '0' '2' '1' '2' '2' '2' '0' '1' '2' '0' '2'
 '1' '1' '1' '0' '1' '1' '1' '0' '2' '0' '0' '2' '2' '0' '0' '2' '1' '1'
 '1' '0' '1' '2' '1' '0' '2' '1' '0' '2' '2' '2' '1' '2' '2' '0' '2' '2'
 '0' '2' '1' '0' '2' '0' '1' '2' '2' '1' '2' '0' '2' '2' '1' '0' '0' '0'
 '2' '0' '1' '1' '2' '1' '1' '1' '2' '1' '2' '0' '1' '2' '0' '1' '1' '0'
 '0' '1' '1' '0' '0' '0' '2' '2' '1' '1' '1' '1' '0' '2' '2' '2' '0' '2'
 '0' '0' '1' '0' '1' '0' '2' '2' '0' '1' '0' '2' '2' '0' '2' '1' '1' '0'
 '0' '2' '2' '1' '0' '1']


In [12]:
# normalizar dados
# x = x / x.max(axis=0)

#### One-Hot Encoding

In [13]:
Y_onehot = np.zeros(shape=[len(y),len(classes)])
print(np.shape(Y_onehot))

for y_index in range(len(y)):
    Y_onehot[y_index, int(y[y_index])] = 1

(150, 3)


In [14]:
print(Y_onehot)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1.

### Split in Train and Test

In [15]:
# train
x_train = np.float32(x[0:100, :])
y_train = Y_onehot[0:100, :]

# test
x_test = np.float32(x[100:150, :])
y_test = Y_onehot[100:150, :]

In [16]:
print(np.shape(x_train))
print(np.shape(y_train))
print(np.shape(x_test))
print(np.shape(y_test))

(100, 4)
(100, 3)
(50, 4)
(50, 3)


In [17]:
print((x_train))
print((y_train))
print((x_test))
print((y_test))

[[5.2 2.7 3.9 1.4]
 [5.8 2.7 5.1 1.9]
 [6.2 2.2 4.5 1.5]
 [5.6 3.  4.1 1.3]
 [5.8 4.  1.2 0.2]
 [6.3 2.5 5.  1.9]
 [5.2 3.4 1.4 0.2]
 [5.7 2.6 3.5 1. ]
 [5.1 2.5 3.  1.1]
 [4.6 3.2 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [5.8 2.8 5.1 2.4]
 [6.  3.4 4.5 1.6]
 [4.8 3.  1.4 0.1]
 [5.1 3.8 1.5 0.3]
 [6.4 3.1 5.5 1.8]
 [6.2 2.9 4.3 1.3]
 [6.5 3.  5.8 2.2]
 [5.5 3.5 1.3 0.2]
 [4.6 3.4 1.4 0.3]
 [4.8 3.4 1.6 0.2]
 [5.7 2.8 4.5 1.3]
 [7.3 2.9 6.3 1.8]
 [4.9 3.1 1.5 0.1]
 [5.6 3.  4.5 1.5]
 [4.6 3.1 1.5 0.2]
 [7.7 2.6 6.9 2.3]
 [6.3 2.3 4.4 1.3]
 [6.9 3.1 5.4 2.1]
 [6.8 3.  5.5 2.1]
 [7.2 3.2 6.  1.8]
 [5.4 3.4 1.7 0.2]
 [5.  2.3 3.3 1. ]
 [7.4 2.8 6.1 1.9]
 [4.5 2.3 1.3 0.3]
 [6.7 3.1 5.6 2.4]
 [6.8 2.8 4.8 1.4]
 [5.8 2.7 3.9 1.2]
 [5.8 2.6 4.  1.2]
 [5.1 3.5 1.4 0.3]
 [6.6 3.  4.4 1.4]
 [5.5 2.6 4.4 1.2]
 [5.5 2.3 4.  1.3]
 [5.1 3.8 1.9 0.4]
 [5.8 2.7 5.1 1.9]
 [4.8 3.1 1.6 0.2]
 [5.  3.4 1.6 0.4]
 [6.3 2.9 5.6 1.8]
 [6.9 3.2 5.7 2.3]
 [5.4 3.9 1.3 0.4]
 [4.9 3.1 1.5 0.1]
 [6.7 3.3 5.7 2.5]
 [6.1 3.  4.

### Create Neural Network with Tensorflow

In [18]:
# reset the model graph
tf.reset_default_graph()

In [19]:
# define variables we will work with
X = tf.placeholder(dtype=tf.float32, shape=[None, 4])
Y = tf.placeholder(dtype=tf.int32, shape=[None, 3])

alpha = tf.placeholder(dtype=tf.float32, shape=None)

In [20]:
# first layer
dense1 = tf.layers.dense(inputs=X, units=20, activation=tf.sigmoid)
dense2 = tf.layers.dense(inputs=dense1, units=8, activation=tf.sigmoid)

In [21]:
# output layer
output = tf.layers.dense(inputs=dense2, units=len(classes), activation=tf.nn.softmax)

In [22]:
# compute loss
loss = tf.losses.softmax_cross_entropy(Y, output)

In [23]:
# optimze network weights
trainer = tf.train.GradientDescentOptimizer(learning_rate=alpha)

train_operation = trainer.minimize(loss)

### Create Session and execute the graph

In [24]:
# Auxiliary functions:
# def compute_accuracy(real, output):
#     pred_real = np.argmax(real ,axis=1)
#     pred_output = np.argmax(output ,axis=1)
    
#     return sum(pred_real==pred_output)/float(len(real))

In [25]:
# Train:
train_epochs = 10000

sess = tf.Session()

In [28]:
# initialize all variables
sess.run(tf.global_variables_initializer())

# Train
for epoch in range(train_epochs):
    output_, loss_, train_operation_ = sess.run([output, loss, train_operation],
                                               feed_dict={X: x_train, Y: y_train,
                                                         alpha: 0.05})
    
    print("epoch {}: {} - Accuracy: {}".format(epoch, loss_, accuracy_score(np.argmax(y_train, axis=1),np.argmax(output_, axis=1))))

epoch 0: 1.1133419275283813 - Accuracy: 0.34
epoch 1: 1.1132267713546753 - Accuracy: 0.34
epoch 2: 1.1131116151809692 - Accuracy: 0.34
epoch 3: 1.1129965782165527 - Accuracy: 0.34
epoch 4: 1.1128816604614258 - Accuracy: 0.34
epoch 5: 1.1127666234970093 - Accuracy: 0.34
epoch 6: 1.1126517057418823 - Accuracy: 0.34
epoch 7: 1.1125367879867554 - Accuracy: 0.34
epoch 8: 1.112421989440918 - Accuracy: 0.34
epoch 9: 1.1123071908950806 - Accuracy: 0.34
epoch 10: 1.1121925115585327 - Accuracy: 0.34
epoch 11: 1.1120778322219849 - Accuracy: 0.34
epoch 12: 1.111963152885437 - Accuracy: 0.34
epoch 13: 1.1118484735488892 - Accuracy: 0.34
epoch 14: 1.1117340326309204 - Accuracy: 0.34
epoch 15: 1.1116193532943726 - Accuracy: 0.34
epoch 16: 1.1115047931671143 - Accuracy: 0.34
epoch 17: 1.1113903522491455 - Accuracy: 0.34
epoch 18: 1.1112759113311768 - Accuracy: 0.34
epoch 19: 1.111161470413208 - Accuracy: 0.34
epoch 20: 1.1110471487045288 - Accuracy: 0.34
epoch 21: 1.1109328269958496 - Accuracy: 0.34
e

In [31]:
# Test
output_, loss_ = sess.run([output, loss], feed_dict={X: x_test, Y: y_test})
    
print(accuracy_score(np.argmax(y_test, axis = 1), np.argmax(output_, axis = 1)))


0.96
